### ISSUE TITLE
Fails to build with Lua 5.2.3: undeclared identifier 'LUA_GLOBALSINDEX'

### ISSUE THREAD

**Issue by sjackman** [tjunier/newick_utils#6]
See [this gist](https://gist.github.com/anonymous/a2f91399f4b15df9d15e#file-02-make-L90-L92) for the complete log.
```
/bin/sh ../libtool --tag=CC   --mode=link clang  -g -O2   -o nw_indent indent.o indent_lex.o  -llua -lxml2 -lm 
lua_tree_editor.c:631:19: error: use of undeclared identifier 'LUA_GLOBALSINDEX'
                lua_getfield(L, LUA_GLOBALSINDEX, NODE);
```
